from typing import Any, Dict, List, Optional, Sequence, Tuple

class Game:
  def num_players(self) -> int: ...
  def get_type(self) -> Any: ...

class State:
  def is_terminal(self) -> bool: ...
  def is_chance_node(self) -> bool: ...
  def is_simultaneous_node(self) -> bool: ...
  def current_player(self) -> int: ...
  def legal_actions(self, player: Optional[int] = ...) -> List[int]: ...
  def apply_action(self, action: int) -> None: ...
  def apply_actions(self, actions: Sequence[int]) -> None: ...
  def returns(self) -> List[float]: ...
  def clone(self) -> State: ...
  def num_players(self) -> int: ...

class Bot:
  def restart_at(self, state: State) -> None: ...
  def step(self, state: State) -> int: ...

INVALID_ACTION: int

def load_game(
    game_string: str,
    parameters: Optional[Dict[str, Any]] = ...,
) -> Game: ...
def deserialize_game_and_state(
    serialized: str,
) -> Tuple[Game, State]: ...
